rm(list = ls())

# Libraries ---------------------------------------------------------------
library(visNetwork)
library(igraph)
library(tidyverse)
library(shiny)
library(readr)

# Environment -------------------------------------------------------------
prod <- TRUE
test <- TRUE # Use the file generated by the test environment
# Defaults to dev environment if no environment is specified, which uses easyNer abstract as data

entity_1 <- "phenomenon"
entity_2 <- "disease"
threshold_fq <- 100
excluded_entity_1 <- c("current", "wave")
excluded_entity_2 <- c("fire")

# File Paths --------------------------------------------------------------
if (prod) {
  name <- "top_50_pre_manual_drop"
  co_occurrence_matrix_file <- "data/processed/entities/cooc50_matrix.csv"
  exported_network_dir <- file.path("data/export/cooccurence_network", name)
  network_file <- file.path(exported_network_dir, "network.html")
  excluded_entities_file <- file.path(exported_network_dir, "excluded_entities.csv")

} else if (test) {
  co_occurrence_matrix_file <- "tests/data/generated/test_cooc50_matrix.csv"
  exported_network_dir <- "tests/data/export/test_cooc50_network"
  network_file <- file.path(exported_network_dir, "network.html")
  excluded_entities_file <- file.path(exported_network_dir, "excluded_entities.csv")
} else {
  message("No environment specified. Defaulting to dev environment.")
  co_occurrence_matrix_file <- "tests/data/generated/co_occurrence_matrix.csv"
  exported_network_dir <- "tests/data/export/network"
  excluded_entities_file <- file.path(exported_network_dir, "excluded_entities.csv")
  network_file <- file.path(exported_network_dir, "network.html")
}


# Create the directories if they do not exist
if (!dir.exists(exported_network_dir)) {
  dir.create(exported_network_dir, recursive = TRUE)
}




# Clense previous data
# if (file.exists(network_file)) {
#   file.remove(network_file)
# }

# Data Preparation --------------------------------------------------------

# Read the co-occurrence matrix from the CSV file
co_occurrence_matrix <- read.csv(co_occurrence_matrix_file, row.names = 1)

# Export excluded entities to a CSV file
excluded_entities <- data.frame(
  entity_1 = excluded_entity_1,
  entity_2 = excluded_entity_2
)
write.csv(excluded_entities, excluded_entities_file, row.names = FALSE)

# Create a pretty table of excluded entities


# Row (entity 1) nodes
row_nodes <- data.frame(
  id = paste(entity_1, rownames(co_occurrence_matrix), sep = "_"),  # Unique identifier with prefix
  label = rownames(co_occurrence_matrix),
  value = rowSums(co_occurrence_matrix > 0), # Must have at least X connections
  group = entity_1)

  # print(row_nodes)
# Column (entity 2) nodes
col_nodes <- data.frame(
  id = paste(entity_2, colnames(co_occurrence_matrix), sep = "_"),  # Unique identifier with prefix
  label = colnames(co_occurrence_matrix),
  value = colSums(co_occurrence_matrix > 0), # Must have at least X connections
  group = entity_2)

  # print(col_nodes)

# Combine row and column nodes
nodes <- rbind(row_nodes, col_nodes)

# Test if all nodes have unique IDs
if (length(unique(nodes$id)) != nrow(nodes)) {
  stop("The nodes data frame has duplicate IDs.")
}


# Create edges data frame
edges <- data.frame()
for (i in seq_len(nrow(co_occurrence_matrix))) {
  for (j in seq_len(ncol(co_occurrence_matrix))) {
    # Only include edges with above a threshold value
    if (co_occurrence_matrix[i, j] > 0) {
      edges <- rbind(edges, data.frame(
        from = paste(entity_1, rownames(co_occurrence_matrix)[i], sep = "_"),
        to = paste(entity_2, colnames(co_occurrence_matrix)[j], sep = "_"),
        value = co_occurrence_matrix[i, j]))
    }
  }
}


# Ensure 'from' and 'to' columns exist in edges data frame
if (!all(c("from", "to") %in% colnames(edges))) {
  stop("The 'from' and 'to' columns are missing in the edges data frame.")
}


# Define colors for groups
group_colors <- list(
  phenomenon = list(background = "#ccac4c", border = "#0d3d48", highlight = "#ffd760"),
  disease = list(background = "#974848", border = "#0d3d48", highlight = "#d65757")
)

# Create the network visualization
network <- visNetwork(nodes, edges, width = "100%", height = "1000px") %>%
  # fix randomSeed to keep positions consistent
  visIgraphLayout(physics = TRUE, smooth = TRUE, randomSeed = 123, layout = "layout_nicely") %>% # This will use the igraph layout that more clearly shows the clusters
  visNodes(
    shape = "dot",
    color = list(
      background = "#67d7b2ad",
      border = "#0d3d48",
      highlight = "#ffd760"
    ),
    shadow = list(enabled = FALSE, size = 5),
    font = list(
      color = "#000000", # Font color
      size = 15, # Font size
      face = "calibri" # Font family
    )
  ) %>%
  visEdges(
    shadow = FALSE,
    color = list(color = "#0cb9b3", highlight = "#fe7e7e"),
    smooth = list(enabled = TRUE, type = "continuous"),
  ) %>%
  visOptions(
    highlightNearest = list(enabled = TRUE, degree = 1, hover = TRUE), # nolint: indentation_linter.
    selectedBy = "group",
    nodesIdSelection = TRUE,
  ) %>%
  visGroups(
    groupname = "phenomenon",
    color = group_colors$phenomenon
  ) %>%
  visGroups(
    groupname = "disease",
    color = group_colors$disease
  ) %>%
  visLayout(randomSeed = 14) %>%
  visPhysics(
    # choose the solver (‘barnesHut’, ‘repulsion’, ‘hierarchicalRepulsion’, ‘forceAtlas2Based’), and set options
    solver = "forceAtlas2Based",
    stabilization = TRUE
  ) %>%
  visLegend(
    addNodes = list(
      list(label = "PNM", shape = "dot", color = group_colors$phenomenon$background),
      list(label = "DIS", shape = "dot", color = group_colors$disease$background)
    ),
    useGroups = FALSE
  )

# Save the network visualization to an HTML file
visSave(network, file = network_file, selfcontained = FALSE)

# Save to png
# visNetwork2png(network, file = "network.png")
# Log info to console
message("Network visualization saved to ", network_file)